### ISSUE TITLE
Why can't the image be displayed at backend?

### ISSUE THREAD

**Issue by taoguangc** [panlatent/craft-aliyun#1]

**Comment by panlatent** [comment]
Please give detailed volume configuration information (note privacy). 

Usually, this is because your public URL does not match the cloud storage path.

Here is a good example:

File: ROOT_PATH/123.png
Set Public URL's : //myproject.com/ROOT_PATH
Set Root Mapping: ROOT_PATH

The Root setting is actually a solution for multiple volumes using one space.

**Comment by taoguangc** [comment]
In asset settings, I add a new volumes.
Name: files
Handle: files
Assets in this volume have public URLs: true
Base URL: http://myBucket.oss-cn-hangzhou.aliyuncs.com/files
......
Endpoint: oss-cn-hangzhou.aliyuncs.com
Bucket: myBucket
Access Control: true
Root Path: files

That's it.
